feature/vite react tailwind app init
JohannaStoicanescu/althea pull request #2
Opened 2024-12-16 15:45 UTC by JohannaStoicanescu

2024-12-16 16:06 UTC, paul-ohl commented
Ras-le-bol de la branche dev, mais bon...

2024-12-16 16:08 UTC, paul-ohl approved these changes

2024-12-16 16:08 UTC, paul-ohl commented on README.md
J'aimais mieux le Readme custom, qu'en penses tu?

2024-12-16 16:13 UTC, JohannaStoicanescu commented on README.md
Tu as complètement raison. Tu peux t'en occuper ? Comme ça t'es pas bloqué le temps que je rentre

2024-12-17 16:03 UTC, paul-ohl requested changes
Met tous les fichiers dans un dossier `front_landing` stp

2024-12-19 10:15 UTC, paul-ohl commented
Not used

2024-12-19 10:15 UTC, closed without merging